# Generated by Django 2.1.5 on 2019-02-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('UeserRoleId', models.AutoField(primary_key=True, serialize=False)),
                ('UserRoleName', models.CharField(max_length=20)),
                ('CreatedBy', models.CharField(max_length=20)),
                ('CreatedOn', models.CharField(max_length=20)),
                ('UpdatedBy', models.CharField(max_length=20)),
                ('UpdatedOn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_UserRole',
            },
        ),
        migrations.AlterField(
            model_name='usersimage',
            name='ImageName',
            field=models.CharField(max_length=50),
        ),
    ]
