# Generated by Django 2.1.5 on 2019-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0002_auto_20190202_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('RolePkId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
                ('isActive', models.BooleanField(default=0)),
                ('CreatedOn', models.CharField(max_length=20)),
                ('CreatedBy', models.CharField(max_length=20)),
                ('ModifiedOn', models.CharField(max_length=20)),
                ('ModifiedBy', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_UserRole',
            },
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='UserRoleId',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersimage',
            name='ImageName',
            field=models.CharField(max_length=20),
        ),
    ]
