# Generated by Django 2.1.5 on 2019-02-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0004_auto_20190204_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserRoles',
        ),
    ]
