# Generated by Django 2.1.5 on 2019-02-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0005_auto_20190204_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
