# Generated by Django 2.1.5 on 2019-02-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0008_mailsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='EmailId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
