# Generated by Django 2.1.5 on 2019-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0009_auto_20190205_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMaster',
            fields=[
                ('PkId', models.AutoField(primary_key=True, serialize=False)),
                ('SentTo', models.CharField(max_length=20)),
                ('CcAcnt', models.TextField()),
                ('BccAcnt', models.TextField()),
                ('Subject', models.TextField()),
                ('Message', models.TextField()),
                ('From', models.CharField(max_length=20)),
                ('SentOn', models.CharField(max_length=20)),
                ('isDelivered', models.BooleanField()),
                ('CreatedOn', models.CharField(max_length=20)),
                ('CreatedBy', models.CharField(max_length=20)),
                ('ModifiedOn', models.CharField(max_length=20)),
                ('ModifiedBy', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_MailMaster',
            },
        ),
        migrations.DeleteModel(
            name='MailSent',
        ),
    ]
