# Generated by Django 2.1.5 on 2019-02-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0012_bloodrquestmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrquestmaster',
            name='CreatedOn',
            field=models.CharField(default='2019-02-22', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrquestmaster',
            name='ModifiedOn',
            field=models.CharField(default='2019-02-22', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrquestmaster',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
