# Generated by Django 2.1.5 on 2019-02-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0013_auto_20190222_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrquestmaster',
            name='ReqStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrquestmaster',
            name='UniqueCode',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
