# Generated by Django 2.1.5 on 2019-03-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0014_auto_20190222_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrquestmaster',
            name='CreatedOn',
            field=models.CharField(default='2019-03-08', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrquestmaster',
            name='ModifiedOn',
            field=models.CharField(default='2019-03-08', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrquestmaster',
            name='ReqStatus',
            field=models.TextField(),
        ),
    ]
