# Generated by Django 2.1.5 on 2019-03-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent', '0016_auto_20190310_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmaster',
            name='isRead',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodrquestmaster',
            name='CreatedOn',
            field=models.CharField(default='2019-03-19', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrquestmaster',
            name='ModifiedOn',
            field=models.CharField(default='2019-03-19', max_length=20),
        ),
        migrations.AlterField(
            model_name='savemailmaster',
            name='CreatedOn',
            field=models.CharField(default='2019-03-19', max_length=20),
        ),
        migrations.AlterField(
            model_name='savemailmaster',
            name='ModifiedOn',
            field=models.CharField(default='2019-03-19', max_length=20),
        ),
    ]
